[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "out"
  exclude = [
    'Footer.html',
    './public/Features.html'
  ]